services:
  app:
    build: app
    restart: unless-stopped
    env_file:
      - .env

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db


volumes:
  mongo-data:
